### ISSUE TITLE
Hessian produces wrong results, but works if I add a perturbation

### ISSUE THREAD

**Issue by tawe141** [pytorch/functorch#1097]
I have the following function I would like the Hessian of: 

```python
def rbf(x1, x2, l):
    diff = x1/l - x2/l
    dist = torch.linalg.norm(diff)
    return torch.exp(-dist * dist)
```

Taking the Hessian with `jacfwd` and `grad` seems to get me an incorrect result on a naive example. According to my derivation by hand, this should return `2.0 / l**2 * torch.eye(16)`. If I add a small number to one of the terms, the Hessian function returns the correct result:

```python
jacfwdgrad_rbf = jacfwd(grad(rbf, argnums=0), argnums=1)  # doing d^2f/dx1dx2

a = torch.randn(16)
l = 1.0

print(torch.allclose(jacfwdgrad_rbf(a, a, l), 2/l/l * torch.eye(16)))  # prints False

print(torch.allclose(jacfwdgrad_rbf(a, a+1e-8, l), 2/l/l * torch.eye(16)))  # prints True
```
Is there some bug that means the former check doesn't work, or is there something I'm missing?

**Comment by tawe141** [comment]
Quick update: using `jacrev` in place of `jacfwd` produces a matrix of `nan`s when I don't perturb and works as expected when I do. Setting `torch.autograd.set_detect_anomaly(True)` gives a traceback for where there might be issues, and here's what came out: 

```
/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/autograd/__init__.py:300: UserWarning: There is a performance drop because we have not yet implemented the batching rule for aten::any. Please file us an issue on GitHub so that we can prioritize its implementation. (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/aten/src/ATen/functorch/BatchedFallback.cpp:82.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/autograd/__init__.py:300: UserWarning: Error detected in DivBackward0. Traceback of forward call that caused the error:
  File "/home/tawe141/mfip/scripts/test_bad_hess.py", line 25, in <module>
    print(torch.allclose(jacrevgrad_rbf(a, a, l), 2/l/l * torch.eye(16)))  # matrix of nans
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 459, in wrapper_fn
    vjp_out = _vjp_with_argnums(func, *args, argnums=argnums, has_aux=has_aux)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 289, in _vjp_with_argnums
    primals_out = func(*primals)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 1241, in wrapper
    results = grad_and_value(func, argnums, has_aux=has_aux)(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 1133, in wrapper
    flat_grad_input = _autograd_grad(flat_outputs, flat_diff_args, create_graph=True)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 113, in _autograd_grad
    grad_inputs = torch.autograd.grad(diff_outputs, inputs, grad_outputs,
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/autograd/__init__.py:300: UserWarning: 

Previous calculation was induced by DivBackward0. Traceback of forward call that induced the previous calculation:
  File "/home/tawe141/mfip/scripts/test_bad_hess.py", line 25, in <module>
    print(torch.allclose(jacrevgrad_rbf(a, a, l), 2/l/l * torch.eye(16)))  # matrix of nans
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 459, in wrapper_fn
    vjp_out = _vjp_with_argnums(func, *args, argnums=argnums, has_aux=has_aux)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 289, in _vjp_with_argnums
    primals_out = func(*primals)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 1241, in wrapper
    results = grad_and_value(func, argnums, has_aux=has_aux)(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 1111, in wrapper
    output = func(*args, **kwargs)
  File "/home/tawe141/mfip/scripts/test_bad_hess.py", line 7, in rbf
    diff = x1 / l - x2 / l
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/fx/traceback.py", line 57, in format_stack
    return traceback.format_stack()
 (Triggered internally at /opt/conda/conda-bld/pytorch_1666642969563/work/torch/csrc/autograd/python_anomaly_mode.cpp:121.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "/home/tawe141/mfip/scripts/test_bad_hess.py", line 25, in <module>
    print(torch.allclose(jacrevgrad_rbf(a, a, l), 2/l/l * torch.eye(16)))  # matrix of nans
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 474, in wrapper_fn
    results = vmap(vjp_fn)(basis)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 362, in wrapped
    return _flat_vmap(
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/vmap.py", line 489, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 323, in wrapper
    result = _autograd_grad(flat_primals_out, flat_diff_primals, flat_cotangents,
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/functorch/_src/eager_transforms.py", line 113, in _autograd_grad
    grad_inputs = torch.autograd.grad(diff_outputs, inputs, grad_outputs,
  File "/home/tawe141/miniconda3/envs/mfip/lib/python3.10/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.
```

**Comment by kshitij12345** [comment]
I think the problem is because `norm` is not differentiable at `0`. IIRC, PyTorch returns sub gradient for `norm` at `0` but has trouble with higher orders.

```python
x = torch.zeros(3, dtype=torch.double, requires_grad=True)
o = torch.linalg.norm(x)
gx = torch.autograd.grad(o, x, retain_graph=True, create_graph=True)[0]
gxx = torch.autograd.grad(gx, x, grad_outputs=torch.ones_like(gx))
print(gx)
print(gxx)
```
Output
```
tensor([0., 0., 0.], dtype=torch.float64, grad_fn=<MulBackward0>)
(tensor([nan, nan, nan], dtype=torch.float64),)
```

Pinging @lezcano will have a better understanding of the same.

Regarding, the failure with `torch.autograd.set_detect_anomaly(True)`, you are right that it detects `nan`'s but unfortunately it fails with incorrect message and it is tracked at https://github.com/pytorch/functorch/issues/1049

**Comment by tawe141** [comment]
Thanks @kshitij12345 , I came up with a workaround that didn't use `norm` and it works great.

**Comment by lezcano** [comment]
Kshiteej is right on the money on the second derivative of `linalg.norm`. As a small note, you may want to use `linalg.vector_norm` as it has cleaner semantics than `linalg.norm`.

At any rate, we could fix this second derivative issue, but given that the OP found a work-around, I'm leaning towards tagging this as low priority.
