### ISSUE TITLE
backward shape error

### ISSUE THREAD

**Issue by hyunwoongko** [pytorch/functorch#487]
how to reproduce?

```python
import torch
from torch.optim import Adam
from transformers import GPT2LMHeadModel
from functorch.compile.compilers import memory_efficient_fusion


model_1 = GPT2LMHeadModel.from_pretrained("gpt2").cuda().train()
optim_1 = Adam(model_1.parameters(), lr=3e-5)

model_2 = GPT2LMHeadModel.from_pretrained("gpt2").cuda().train()
optim_2 = Adam(model_2.parameters(), lr=3e-5)
model_2 = memory_efficient_fusion(model_2)

for _ in range(1000):
    input = torch.ones(1, 64, requires_grad=True).long().to("cuda")
    labels = torch.ones(1, 64, requires_grad=True).long().to("cuda")

    out_1 = model_1(input, labels=labels).loss
    out_2 = model_2(input, labels=labels)  # PythonTensor object = loss

    out_1.backward()
    out_2.backward()

    optim_1.step()
    optim_2.step()

    print("fusion", out_1)
    print("non-fusion", out_2)
    print()

```

```
Traceback (most recent call last):
  File "__init__.py", line 22, in <module>
    out_2.backward()
  File "/opt/conda/lib/python3.7/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/lib/python3.7/site-packages/torch/autograd/__init__.py", line 156, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag
RuntimeError: Function CompiledFunctionBackward returned an invalid gradient at index 0 - got [1, 64, 50257] but expected shape compatible with [50257, 768]
```

**Comment by hyunwoongko** [comment]
When I registered modeling output, it worked.

But PythonTensor.backward() can not be used?

**Comment by Chillee** [comment]
Things seem to go quite wrong when the returned output is not a recognizable pytree - this check I added on functorch nightly should catch it (https://github.com/pytorch/functorch/issues/475#issuecomment-1035983774), but I haven't dug into *why* this issue occurs.
