### ISSUE TITLE
vmap over advanced indexing issue

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#508]
```
import torch
from functorch import vmap

def f_test(x, label):
    coeffs = [1, 2, 3, 4, 5]

    return coeffs[label] * x

a = torch.tensor([[1., 1., 1.], [2., 2., 2.]], requires_grad=True)
b = torch.tensor([[2, 3]])

vmap(f_test)(a, b.T)
```

Gives:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/home/rzou/functorch3/functorch/_src/vmap.py", line 353, in wrapped
    batched_outputs = func(*batched_inputs, **kwargs)
  File "<stdin>", line 4, in f_test
RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.
```

Advanced indexing is a pretty important operation. I'm a bit worried we may need to rewrite/refactor how advanced indexing works in pytorch/pytorch to get this to work.

**Comment by zou3519** [comment]
Originally reported at https://discuss.pytorch.org/t/torch-vmap-batching-rule-not-implemented-for-aten-item-we-could-not-generate-a-fallback/144407

**Comment by zou3519** [comment]
Okay, I just realized what is happening here. The problem isn't advanced indexing, the problem is we are vmapping over a Tensor and using it to index into a Python list.

If we were to turn the Python list into a torch.Tensor, this would work:
```
import torch
from functorch import vmap

def f_test(x, label):
    coeffs = torch.tensor([1, 2, 3, 4, 5])
    return coeffs[label] * x

a = torch.tensor([[1., 1., 1.], [2., 2., 2.]], requires_grad=True)
b = torch.tensor([[2, 3]])

vmap(f_test)(a, b.T)
```

**Comment by yhl48** [comment]
Hi, I have the same issue but it only occurs when ``torch.autograd.set_detect_anomaly(True)`` is set. Is this an expected behaviour?
