### ISSUE TITLE
`make_fx` segfaults with functionalization pass

### ISSUE THREAD

**Issue by Chillee** [pytorch/functorch#635]
```
from functorch.experimental import functionalize
from functorch import make_fx

def h2(x):
    return x * 2

make_fx(functionalize(h2))(torch.randn(4, 2))
```
segfaults.

Top 50 stack frames.
```
#0  c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::retain_ (this=<optimized out>) at ../c10/util/intrusive_ptr.h:272
#1  c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::intrusive_ptr (rhs=..., this=<optimized out>) at ../c10/util/intrusive_ptr.h:356
#2  at::TensorBase::TensorBase (this=<optimized out>) at ../aten/src/ATen/core/TensorBase.h:99
#3  at::Tensor::Tensor (tensor=..., this=<optimized out>) at aten/src/ATen/core/TensorBody.h:101
#4  at::functionalization::impl::from_functional_tensor (tensor=...) at ../aten/src/ATen/FunctionalTensorWrapper.cpp:255
#5  0x00007fffbf4f7756 in (anonymous namespace)::functionalizeFallback (op=..., dispatchKeySet=..., stack=0x7fffffff82f0) at ../aten/src/ATen/FunctionalizeFallbackKernel.cpp:20
#6  0x00007fffc1ed62b5 in c10::KernelFunction::callBoxed (stack=0x7fffffff82f0, dispatchKeySet=..., opHandle=..., this=<optimized out>) at ../aten/src/ATen/core/boxing/KernelFunction_impl.h:50
#7  c10::Dispatcher::callBoxed (this=<optimized out>, op=..., stack=0x7fffffff82f0) at ../aten/src/ATen/core/dispatch/Dispatcher.h:589
#8  0x00007fffca3bab3f in std::function<void (std::vector<c10::IValue, std::allocator<c10::IValue> >&)>::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >&) const (
    __args#0=std::vector of length 2, capacity 2 = {...}, this=0x7fffffff8340) at /usr/include/c++/7/bits/std_function.h:706
#9  torch::jit::Operation::operator() (stack=std::vector of length 2, capacity 2 = {...}, this=0x7fffffff8340) at ../aten/src/ATen/core/stack.h:41
#10 torch::jit::invokeOperatorFromPython (operations=std::vector of length 1, capacity 1 = {...}, args=..., kwargs=...) at ../torch/csrc/jit/python/pybind_utils.h:1159
#11 0x00007fffca3bafb8 in torch::jit::_get_operation_for_overload_or_packet (operations=std::vector of length 1, capacity 1 = {...}, symbol=..., args=..., kwargs=..., 
    is_overload=is_overload@entry=true) at ../torch/csrc/jit/python/pybind_utils.h:1229
#12 0x00007fffca3911cb in torch::jit::<lambda(const string&, const string&)>::<lambda(pybind11::args, pybind11::kwargs)>::operator() (kwargs=..., args=..., __closure=0x555558a46b68)
    at ../torch/csrc/jit/python/init.cpp:1256
#13 pybind11::detail::argument_loader<pybind11::args, pybind11::kwargs>::call_impl<pybind11::object, torch::jit::initJITBindings(PyObject*)::<lambda(const string&, const string&)>::<lambda(pybind11::args, pybind11::kwargs)>&, 0, 1, pybind11::detail::void_type> (f=..., this=0x7fffffff85b0) at ../cmake/../third_party/pybind11/include/pybind11/cast.h:2042
#14 pybind11::detail::argument_loader<pybind11::args, pybind11::kwargs>::call<pybind11::object, pybind11::detail::void_type, torch::jit::initJITBindings(PyObject*)::<lambda(const string&, const string&)>::<lambda(pybind11::args, pybind11::kwargs)>&> (f=..., this=<optimized out>) at ../cmake/../third_party/pybind11/include/pybind11/cast.h:2014
#15 pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::operator() (__closure=0x0, call=...) at ../cmake/../third_party/pybind11/include/pybind11/pybind11.h:192
#16 pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::_FUN(pybind11::detail::function_call &) () at ../cmake/../third_party/pybind11/include/pybind11/pybind11.h:170
#17 0x00007fffca03c437 in pybind11::cpp_function::dispatcher (self=<optimized out>, args_in=0x7fff4e812380, kwargs_in=0x7fff4e823b40)
    at ../cmake/../third_party/pybind11/include/pybind11/pybind11.h:767
#18 0x00005555556907ae in cfunction_call_varargs () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:743
#19 0x000055555572f6a6 in PyCFunction_Call (kwargs=0x7fff4e823b40, args=0x7fff4e812380, func=0x7fff4eb22ea0) at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:773
#20 do_call_core (kwdict=0x7fff4e823b40, callargs=0x7fff4e812380, func=0x7fff4eb22ea0, tstate=<optimized out>) at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:4983
#21 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:3559
#22 0x00005555557201f0 in PyEval_EvalFrameEx (throwflag=0, f=0x7fff4e817dc0) at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:741
#23 _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:4298
#24 0x00005555557217b4 in _PyFunction_Vectorcall () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:436
#25 0x00005555556b2797 in _PyObject_FastCallDict () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:104
#26 0x00005555556e8bbb in _PyObject_Call_Prepend (kwargs=0x7fff4e823740, args=0x7fff4e80f780, obj=<optimized out>, callable=0x7fff5178db80)
    at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:888
#27 slot_tp_call () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/typeobject.c:6556
#28 0x000055555568b95d in PyObject_Call () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:246
#29 0x000055555572b823 in do_call_core (kwdict=0x7fff4e823740, callargs=0x7fff4e80f780, func=0x7fff4e822850, tstate=<optimized out>)
    at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:5010
#30 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:3559
#31 0x0000555555720cef in PyEval_EvalFrameEx (throwflag=0, f=0x555558ab3270) at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:741
---Type <return> to continue, or q <return> to quit---
#32 _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python-split_1634043551344/work/Python/ceval.c:4298
#33 0x00005555557217b4 in _PyFunction_Vectorcall () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:436
#34 0x00005555556baca8 in _PyObject_Vectorcall (kwnames=0x0, nargsf=5, args=0x7fffffff9000, callable=0x7fff5084f040)
    at /tmp/build/80754af9/python-split_1634043551344/work/Include/cpython/abstract.h:127
#35 method_vectorcall () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/classobject.c:89
#36 0x0000555555696e24 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7fffffff90a0, callable=0x7fff51567d40)
    at /tmp/build/80754af9/python-split_1634043551344/work/Include/cpython/abstract.h:127
#37 _PyObject_FastCall () at /tmp/build/80754af9/python-split_1634043551344/work/Include/cpython/abstract.h:147
#38 object_vacall () at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:1187
#39 0x0000555555696fde in PyObject_CallFunctionObjArgs (callable=<optimized out>) at /tmp/build/80754af9/python-split_1634043551344/work/Objects/call.c:1260
#40 0x00007fffca62f456 in torch::handle_torch_function_no_python_arg_parser (overloaded_args=std::vector of length 1, capacity 1 = {...}, args=0x7fff4e80f780, kwargs=0x7fff4e823740, 
    func_name=func_name@entry=0x555555d6d0f6 "mul", torch_api_function=torch_api_function@entry=0x7fff4e822850, module_name=0x7fffffff9610 "torch.ops.aten", 
    torch_function_name=0x7fffca759072 "__torch_dispatch__") at ../torch/csrc/utils/python_arg_parser.cpp:234
#41 0x00007fffca357553 in (anonymous namespace)::concrete_dispatch_fn (op=..., stack=0x7fffffffa2c0, type=...) at ../torch/csrc/autograd/python_variable.cpp:1818
#42 0x00007fffbf5ca234 in c10::impl::PyInterpreter::dispatch (type=std::shared_ptr<c10::TorchDispatchTypeObject> (empty) = {...}, stack=0x7fffffffa2c0, op=..., this=<optimized out>)
    at ../c10/core/TensorImpl.h:316
#43 (anonymous namespace)::pythonFallback (op=..., stack=0x7fffffffa2c0) at ../aten/src/ATen/core/PythonFallbackKernel.cpp:82
#44 0x00007fffbf5c9e28 in c10::KernelFunction::callBoxed (stack=0x7fffffffa2c0, dispatchKeySet=..., opHandle=..., this=<optimized out>) at ../aten/src/ATen/core/boxing/KernelFunction_impl.h:50
#45 c10::Dispatcher::redispatchBoxed (this=<optimized out>, stack=0x7fffffffa2c0, dispatchKeySet=..., op=...) at ../aten/src/ATen/core/dispatch/Dispatcher.h:596
#46 c10::OperatorHandle::redispatchBoxed (stack=0x7fffffffa2c0, ks=..., this=0x7fffc99a4df0 <at::_ops::mul_Tensor::redispatch(c10::DispatchKeySet, at::Tensor const&, at::Tensor const&)::op>)
    at ../aten/src/ATen/core/dispatch/Dispatcher.h:369
#47 (anonymous namespace)::pythonTLSSnapshotFallback (stack=0x7fffffffa2c0, dispatch_keys=..., op=...) at ../aten/src/ATen/core/PythonFallbackKernel.cpp:106
#48 c10::KernelFunction::make_boxed_function<(anonymous namespace)::pythonTLSSnapshotFallback> (opHandle=..., ks=..., stack=0x7fffffffa2c0) at ../aten/src/ATen/core/boxing/KernelFunction_impl.h:34
#49 0x00007fff50d91052 in c10::KernelFunction::callBoxed (stack=0x7fffffffa2c0, dispatchKeySet=..., opHandle=..., this=<optimized out>)
    at /fsx/users/chilli/work/pytorch/torch/include/ATen/core/boxing/KernelFunction_impl.h:50
#50 c10::Dispatcher::callBoxed (stack=<optimized out>, op=..., this=<optimized out>) at /fsx/users/chilli/work/pytorch/torch/include/ATen/core/dispatch/Dispatcher.h:589
```

**Comment by Chillee** [comment]
cc: @bdhirsh
