### ISSUE TITLE
NGC 22.02 and NGC 22.03 fails to compile functorch

### ISSUE THREAD

**Issue by jramapuram** [pytorch/functorch#663]
When using [NGC 22.02](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-02.html#rel_22-02) (based off pytorch 1.11.0) and NGC 22.03 (pytorch 1.12.0) functorch fails to compile with the following error:

```bash

/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h: In function ‘at::Tensor at::functorch::gelu_backward_generated_plumbing(const at::Tensor&, const at::Tensor&)’:
/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h:9875:45: error: no matching function for call to ‘at::_ops::gelu_backward::call(const at::Tensor&, const at::Tensor&)’
 9875 |     return ATEN_FN(gelu_backward)(grad, self);
      |                                             ^
In file included from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/ops/gelu_backward.h:20,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/Functions.h:599,
                 from /opt/conda/lib/python3.8/site-packages/torch/include/ATen/ATen.h:15,
                 from /tmp/functorch/functorch/csrc/BatchRulesHelper.h:8,
                 from /tmp/functorch/functorch/csrc/BatchRulesScatterOps.cpp:7:
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/ops/gelu_backward_ops.h:60:21: note: candidate: ‘static at::Tensor at::_ops::gelu_backward::call(const at::Tensor&, const at::Tensor&, c10::string_view)’
   60 |   static at::Tensor call(const at::Tensor & grad_output, const at::Tensor & self, c10::string_view approximate);
      |                     ^~~~
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/ops/gelu_backward_ops.h:60:21: note:   candidate expects 3 arguments, 2 provided
In file included from /tmp/functorch/functorch/csrc/BatchRulesHelper.h:9,
                 from /tmp/functorch/functorch/csrc/BatchRulesScatterOps.cpp:7:
/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h: In function ‘at::Tensor at::functorch::scatter_reduce_two_generated_plumbing(const at::Tensor&, int64_t, const at::Tensor&, c10::string_view, c10::optional<long int>)’:
/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h:15725:21: error: ‘at::_ops::scatter_reduce_two’ has not been declared
15725 |     return ATEN_FN2(scatter_reduce, two)(self, dim, index, reduce, output_size);
      |                     ^~~~~~~~~~~~~~
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/Operators.h:1124:47: note: in definition of macro ‘ATEN_FN2’
 1124 | #define ATEN_FN2(op_name, overload) at::_ops::op_name##_##overload::call
      |                                               ^~~~~~~
/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h: In function ‘at::Tensor& at::functorch::_index_copy__generated_plumbing(at::Tensor&, int64_t, const at::Tensor&, const at::Tensor&)’:
/tmp/functorch/functorch/csrc/VmapGeneratedPlumbing.h:19628:20: error: ‘at::_ops::_index_copy_’ has not been declared
19628 |     return ATEN_FN(_index_copy_)(self, dim, index, source);
      |                    ^~~~~~~~~~~~
/opt/conda/lib/python3.8/site-packages/torch/include/ATen/Operators.h:1125:36: note: in definition of macro ‘ATEN_FN’
 1125 | #define ATEN_FN(op_name) at::_ops::op_name::call
      |                                    ^~~~~~~
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1726, in _run_ninja_build
    subprocess.run(
  File "/opt/conda/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
 
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "setup.py", line 126, in <module>
    setup(
  File "/opt/conda/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/dist.py", line 1214, in run_command
    super().run_command(command)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 120, in build_extensions
    super().build_extensions(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
    build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
    _build_ext.build_extension(self, ext)
  File "/opt/conda/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1405, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1742, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

Built via:
```bash
FUNCTORCH_VERSION=0.1.0  # also tried master

# Install functorch
git clone --recursive https://github.com/pytorch/functorch
cd functorch
git fetch --all --tags
git checkout tags/v${FUNCTORCH_VERSION}
git submodule sync
git submodule update --init --recursive --jobs 0
BUILD_VERSION=${FUNCTORCH_VERSION} /opt/conda/bin/python setup.py install
```

A pip install also doesn't work (need to specify `--no-dependencies`)
```bash

Step 18/44 : RUN /opt/conda/bin/python -c "import functorch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/functorch/__init__.py", line 7, in <module>
    from . import _C
ImportError: /opt/conda/lib/python3.8/site-packages/functorch/_C.so: undefined symbol: _ZNK5torch8autograd4Node4nameEv
```

**Comment by zou3519** [comment]
Thanks for the issue, @jramapuram. NGC 22.02 seems to be built off of the PyTorch 1.11 release, so it should work, but clearly doesn't. This warrants more investigation from our side

**Comment by vfdev-5** [comment]
NGC 22.02 corresponds to https://github.com/pytorch/pytorch/commit/17540c5c and corresponding functorch commit may be https://github.com/pytorch/functorch/commit/3f9ac9d8b3264da8d9b657e679c55c8e709e814b

As for NGC 22.03, I tried the docker image and could install the following version of functorch:
```
pip install git+https://github.com/pytorch/functorch.git@a9edebc4ec1e4c4210e8290e5248b5e78425b5a4

python -c "import functorch as ft; print(ft.__version__)"
0.2.0a0+a9edebc
```

**Comment by jramapuram** [comment]
Thanks for the quick response @vfdev-5 ! Will give the https://github.com/pytorch/functorch/commit/3f9ac9d8b3264da8d9b657e679c55c8e709e814b commit a shot. 

For future reference: what is the way to find the pytorch <--> functorch binding commit?

**Comment by vfdev-5** [comment]
> For future reference: what is the way to find the pytorch <--> functorch binding commit?

I compared it by the dates. NGC container reports pytorch commit -> date => find functorch commit near this date. Basically, this could even work for later functorch commit, but not always especiallly when pytorch introduces some breaking changes and thus functorch couldn't be built

**Comment by jramapuram** [comment]
Thanks @vfdev-5! Commit https://github.com/pytorch/functorch/commit/3f9ac9d8b3264da8d9b657e679c55c8e709e814b does indeed work for NGC 22.02

@zou3519 : wonder if we can suggest functorch be baked into NGC natively? 🤔 . High performant containers with RDMA / etc save a lot of headache for deployments.

**Comment by vfdev-5** [comment]
> wonder if we can suggest functorch be baked into NGC natively?

@ptrblck do you think this could be possible ?

**Comment by ptrblck** [comment]
Thanks for pinging and this feature request. I'm happy to discuss it internally and get back to you :)

**Comment by jramapuram** [comment]
For anyone that needs it NGC 22.02 works with functorch upto commit 489612eeb151680e298f09d4f09ea740d8883b71
