### ISSUE TITLE
Type of objects of subclasses of torch.Tensor are stripped and lost

### ISSUE THREAD

**Issue by huyaoyu** [pytorch/functorch#712]
Functions like `jacrev` and `vmap` strip the type of an object down to `torch.Tensor`.

- PyTorch version: 1.11.0+cu113
- functorch version: 0.1.0
- On Ubuntu 20.04, with Python 3.8.10

Let class `MyTensor` be a subclass of `torch.Tensor`. Let `x` be an instance of `MyTensor`. When calling `jacrev` with `x`, the type of `x` is stripped down to `torch.Tensor`.

The following code reproduces the issue.

```python
import torch
from functorch import jacrev

class MyTensor(torch.Tensor):
    def __init__(self, *args, **kwargs):
        pass

    @staticmethod
    def __new__(cls, *args, **kwargs):
        return super().__new__(cls, *args, **kwargs)

    def my_func(self):
        # A dummy function.
        return self

if __name__ == '__main__':
    x = MyTensor((2,))
    y = torch.Tensor((42,))

    f = lambda a, b: a.my_func() * b
    print(f(x, y))

    # This triggers the error.
    j = jacrev(f)(x, y)

    # # The followings are OK.
    # x = torch.Tensor((2,))
    # f = lambda a, b: a * b
    # j = jacrev(f)(x, y)

    print(j)

```

Expected output:
```
tensor([84.])
tensor([[42.]])
```

The error:
```
Traceback (most recent call last):
  File "for_functorch_issue.py", line 23, in <module>
    j = jacrev(f)(x, y)
  File "/home/yaoyuh/VEs/functorch/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 414, in wrapper_fn
    vjp_out = vjp(f_wrapper, *primals, has_aux=has_aux)
  File "/home/yaoyuh/VEs/functorch/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 243, in vjp
    primals_out = func(*diff_primals)
  File "/home/yaoyuh/VEs/functorch/lib/python3.8/site-packages/functorch/_src/eager_transforms.py", line 597, in f_wrapper
    return f(*replaced_args)
  File "for_functorch_issue.py", line 19, in <lambda>
    f = lambda a, b: a.my_func() * b
AttributeError: 'Tensor' object has no attribute 'my_func
```

A similar error occurs with `vmap` function.

Should functions like `jacrev` and `vmap` keep the original type of the input arguments?

**Comment by zou3519** [comment]
Thanks for the issue, @huyaoyu. There is a "blessed" way to create Tensor subclasses in PyTorch that preserve subclasses when passed into APIs that are implemented with C++ (like functorch).  It is currently a prototype feature we have called `__torch_dispatch__`.

@huyaoyu could you let us know a little more about your use case? What are you subclassing Tensor to do?

cc @albanD @ezyang @Chillee is there a good resource or example for torch_dispatch right now?

**Comment by albanD** [comment]
Hey!

https://dev-discuss.pytorch.org/t/what-and-why-is-torch-dispatch/557 should be a good intro
