### ISSUE TITLE
`NotImplementedError: Cannot copy out of meta tensor; no data!` with `functorch.make_functional`

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/functorch#793]
I am trying to include a functional in another torch.nn.Module (for a hypernetwork implementation), but it's currently a bit inconvenient to do that. Here's an example code:

```python
import torch, functorch

class MyModule(torch.nn.Module):
    def __init__(self, module: torch.nn.Module) -> None:
        super().__init__()
        self._func, _ = functorch.make_functional(module)

mod1 = torch.nn.Linear(3, 4)
mymod = MyModule(mod1)

# let's say MyModule contains another non-functional module that we want to move
# just to make the line below makes sense
mymod.to(torch.device('cpu'))  # raises the said error
```

The last line above would raise an error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 907, in to
    return self._apply(convert)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 578, in _apply
    module._apply(fn)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 601, in _apply
    param_applied = fn(param)
  File "/home/ubuntu/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py", line 905, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
NotImplementedError: Cannot copy out of meta tensor; no data!
```

With this error, it prevents me to include the functional module in the other module (because I want to move the module around).
I can do a little bit workaround by calling `functorch.make_functional` in the forward call, but this adds another overhead.
I'm not sure what's the best solution for this, but if we can do this, implementing hypernetwork in pytorch would be much easier!

**Comment by Chillee** [comment]
Haha, this is kind of a dumb issue, if I understand correctly.

Basically, `make_functional` returns a "functional" `nn.Module` (that doesn't actually have any params on it). But... PyTorch still thinks it's an `nn.Module`, and so applies the typical module-y things to it.

So, an ~~stupid~~ easy solution would simply be to prevent PyTorch from registering it as a module.

```
class MyModule(torch.nn.Module):
    def __init__(self, module: torch.nn.Module) -> None:
        super().__init__()
        self._func = [functorch.make_functional(module)[0]]
```

**Comment by llx-08** [comment]
Maybe you could try using huggingface/accelerate to load the actual weight to your module
[https://github.com/huggingface/accelerate](url)

```
from accelerate.utils import named_module_tensors, set_module_tensor_to_device
...
for name, _ in named_module_tensors(module):
    set_module_tensor_to_device(module, name, your_execution_device)
```
