### ISSUE TITLE
test_tensor_ctor_inside_grad is failing on cuda on master

### ISSUE THREAD

**Issue by samdow** [pytorch/functorch#806]
The skip is buried a little bit (also I couldn't get an xfail working and then kinda gave up), so making an issue so that we don't lose it. This seems weird but the stack trace we're seeing:

```
Traceback (most recent call last):
  File "/home/circleci/project/env/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
    method(*args, **kwargs)
  File "/home/circleci/project/env/lib/python3.7/site-packages/torch/testing/_internal/common_utils.py", line 1808, in wrapper
    method(*args, **kwargs)
  File "/home/circleci/project/env/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 390, in instantiated_test
    raise rte
  File "/home/circleci/project/env/lib/python3.7/site-packages/torch/testing/_internal/common_device_type.py", line 377, in instantiated_test
    result = test(self, **param_kwargs)
  File "test/test_eager_transforms.py", line 821, in test_tensor_ctor_inside_grad
    functorch.grad(foo)(x)
  File "/home/circleci/project/functorch/_src/eager_transforms.py", line 1192, in wrapper
    results = grad_and_value(func, argnums, has_aux=has_aux)(*args, **kwargs)
  File "/home/circleci/project/functorch/_src/eager_transforms.py", line 1062, in wrapper
    output = func(*args, **kwargs)
  File "test/test_eager_transforms.py", line 818, in foo
    return x * torch.tensor(2., device=device)
RuntimeError: Cannot access data pointer of Tensor that doesn't have storage
```

**Comment by zou3519** [comment]
new at::lift in tensor_new is looking suspicious, https://github.com/pytorch/pytorch/pull/77285 . I'm still looking into it, but any initial thoughts, @bdhirsh ?

**Comment by bdhirsh** [comment]
I ran `test_eager_transforms.py` locally with that change before I landed it, but this does look suspicious. Taking a look now.

**Comment by samdow** [comment]
I can also add a little more color if it's helpful:
- A bunch of `_masked.X` tests also started failing with the same failure. Similarly only on CUDA (#804)
- This showed up between the 5/12 nightly and 5/13 nightly. So it should be in a commit between https://github.com/pytorch/pytorch/commit/188854eeaf148b685e54a438fa7b9a20d3a28e33 and https://github.com/pytorch/pytorch/commit/65f71c0cbeb080c13e927d37b0d23d39bac6f092

**Comment by samdow** [comment]
Looks like this (plus all the other failures in #804) are fixed. Thanks @bdhirsh!
