### ISSUE TITLE
test_vmapjvpall_nn_functional_embedding_cuda_float32 gives incorrect values

### ISSUE THREAD

**Issue by zou3519** [pytorch/functorch#857]
```
======================================================================
FAIL: test_vmapjvpall_nn_functional_embedding_cuda_float32 (__main__.TestOperatorsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1818, in wrapper
    method(*args, **kwargs)
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 1818, in wrapper
    method(*args, **kwargs)
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 377, in in
stantiated_test
    result = test(self, **param_kwargs)
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_internal/common_device_type.py", line 786, in te
st_wrapper
    return test(*args, **kwargs)
  File "/private/home/rzou/functorch4/test/test_ops.py", line 819, in test_vmapjvpall
    self.assertEqual(loop_out, batched_out)
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_internal/common_utils.py", line 2250, in assertE
qual
    assert_equal(
  File "/raid/rzou/pt/binaries4-env/lib/python3.10/site-packages/torch/testing/_comparison.py", line 1095, in assert_equal
    raise error_metas[0].to_error(msg)
AssertionError: Tensor-likes are not close!

Mismatched elements: 54 / 80 (67.5%)
Greatest absolute difference: 0.10568693280220032 at index (0, 0, 0, 2) (up to 0.0001 allowed)
Greatest relative difference: 0.257446934646582 at index (0, 0, 1, 4) (up to 0.0001 allowed)

The failure occurred for item [0]
```
To repro:
- make sure the test isn't skipped
- run the above command

**Comment by zou3519** [comment]
This is just a testing problem from our side.
